//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int AppUserId { get; set; }
        public string AppUserName { get; set; }
        public string AppPassword { get; set; }
        public Nullable<System.Guid> Id { get; set; }
        public string UserName { get; set; }
    }
}
